site_name: PikeConsole - Documentation
theme:
    name: material
    palette:
        scheme: slate
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.indexes

markdown_extensions:
    - pymdownx.superfences
    - def_list
    - pymdownx.blocks.admonition
    - pymdownx.blocks.details
    - pymdownx.keys
    - pymdownx.tabbed:
          alternate_style: true

nav:
    - Home: index.md
    - Guides:
          - Overview: guides/index.md
          - Getting Started: guides/getting_started.md
          - Logging: guides/logging.md
          - Commands: guides/commands.md
          - CVars: guides/cvars.md
          - Aliases: guides/aliases.md
          - Best Practices: guides/best_practices.md
          - Video Guides: guides/video_guides.md
    - API Reference:
          - Overview: api/index.md
          - Logging:
                - LogEvent: api/Logging/LogEvent.md
                - LogLevel: api/Logging/LogLevel.md
                - LogTarget: api/Logging/LogTarget.md
                - PikeLogger: api/Logging/PikeLogger.md
          - Runtime Execution:
                - Commands:
                      - CommandSet: api/RuntimeExecution/Commands/CommandSet.md
                - CVars:
                      - Extensions:
                            - CVarBase<T>: api/RuntimeExecution/CVars/Extensions/CVarBase_T.md
                      - CVarBool: api/RuntimeExecution/CVars/CVarBool.md
                      - CVarDouble: api/RuntimeExecution/CVars/CVarDouble.md
                      - CVarEnum: api/RuntimeExecution/CVars/CVarEnum.md
                      - CVarFloat: api/RuntimeExecution/CVars/CVarFloat.md
                      - CVarInt: api/RuntimeExecution/CVars/CVarInt.md
                      - CVarString: api/RuntimeExecution/CVars/CVarString.md
                      - CVarColor: api/RuntimeExecution/CVars/CVarColor.md
                      - CVarVector2: api/RuntimeExecution/CVars/CVarVector2.md
                      - CVarVector2I: api/RuntimeExecution/CVars/CVarVector2I.md
                      - CVarVector3: api/RuntimeExecution/CVars/CVarVector3.md
                      - CVarVector3I: api/RuntimeExecution/CVars/CVarVector3I.md
                - Configs:
                      - UserConfigManager: api/RuntimeExecution/Configs/UserConfigManager.md
                      - ConfigIO: api/RuntimeExecution/Configs/ConfigIO.md
                      - ConfigRef: api/RuntimeExecution/Configs/ConfigRef.md
                      - ConfigResponseStatus: api/RuntimeExecution/Configs/ConfigResponseStatus.md
                - PersistentCVarRegistry: api/RuntimeExecution/PersistentCVarRegistry.md
                - RegistryBrowser: api/RuntimeExecution/RegistryBrowser.md
                - SearchMode: api/RuntimeExecution/SearchMode.md
                - StatementExecutor: api/RuntimeExecution/StatementExecutor.md
                - ExecutionSource: api/RuntimeExecution/ExecutionSource.md
                - StatementParser: api/RuntimeExecution/StatementParser.md
                - ParsedStatement: api/RuntimeExecution/ParsedStatement.md
                - ArgumentParser: api/RuntimeExecution/ArgumentParser.md
                - IRuntimeExecutable: api/RuntimeExecution/IRuntimeExecutable.md
                - ICVar: api/RuntimeExecution/ICVar.md
                - Response<T>: api/RuntimeExecution/Response_T.md
                - ExecutionResponseStatus: api/RuntimeExecution/ExecutionResponseStatus.md
                - CvarSetResponseStatus: api/RuntimeExecution/CvarSetResponseStatus.md
